{{- if .Values.exposeRoute }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "app.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ include "app.fullname" . }}
  tls:
    termination: edge
{{- end }}
